// SPDX-License-Identifier: BSD-3-Clause
// Copyright (c) Jahred Love. All rights reserved.

#ifndef JELLO_INTERNAL_MATH_H
#define JELLO_INTERNAL_MATH_H

#include <stdint.h>

struct exec_ctx;
struct jello_insn;

/* Must match jelloc/src/jlo/format.rs NATIVE_BUILTIN_MATH_* (12..45). */
#define JELLO_NATIVE_BUILTIN_MATH_ABS 12u
#define JELLO_NATIVE_BUILTIN_MATH_CEIL 13u
#define JELLO_NATIVE_BUILTIN_MATH_FLOOR 14u
#define JELLO_NATIVE_BUILTIN_MATH_ROUND 15u
#define JELLO_NATIVE_BUILTIN_MATH_TRUNC 16u
#define JELLO_NATIVE_BUILTIN_MATH_CBRT 17u
#define JELLO_NATIVE_BUILTIN_MATH_EXP 18u
#define JELLO_NATIVE_BUILTIN_MATH_EXPM1 19u
#define JELLO_NATIVE_BUILTIN_MATH_LOG 20u
#define JELLO_NATIVE_BUILTIN_MATH_LOG1P 21u
#define JELLO_NATIVE_BUILTIN_MATH_LOG10 22u
#define JELLO_NATIVE_BUILTIN_MATH_LOG2 23u
#define JELLO_NATIVE_BUILTIN_MATH_POW 24u
#define JELLO_NATIVE_BUILTIN_MATH_SIN 25u
#define JELLO_NATIVE_BUILTIN_MATH_COS 26u
#define JELLO_NATIVE_BUILTIN_MATH_TAN 27u
#define JELLO_NATIVE_BUILTIN_MATH_ASIN 28u
#define JELLO_NATIVE_BUILTIN_MATH_ACOS 29u
#define JELLO_NATIVE_BUILTIN_MATH_ATAN 30u
#define JELLO_NATIVE_BUILTIN_MATH_ATAN2 31u
#define JELLO_NATIVE_BUILTIN_MATH_SINH 32u
#define JELLO_NATIVE_BUILTIN_MATH_ASINH 33u
#define JELLO_NATIVE_BUILTIN_MATH_COSH 34u
#define JELLO_NATIVE_BUILTIN_MATH_ACOSH 35u
#define JELLO_NATIVE_BUILTIN_MATH_TANH 36u
#define JELLO_NATIVE_BUILTIN_MATH_ATANH 37u
#define JELLO_NATIVE_BUILTIN_MATH_MAX 38u
#define JELLO_NATIVE_BUILTIN_MATH_MIN 39u
#define JELLO_NATIVE_BUILTIN_MATH_RANDOM 40u
#define JELLO_NATIVE_BUILTIN_MATH_CLZ32 41u
#define JELLO_NATIVE_BUILTIN_MATH_FROUND 42u
#define JELLO_NATIVE_BUILTIN_MATH_HYPOT 43u
#define JELLO_NATIVE_BUILTIN_MATH_IMUL 44u
#define JELLO_NATIVE_BUILTIN_MATH_SIGN 45u

void jello_invoke_math_native(struct exec_ctx* ctx, const struct jello_insn* ins, uint32_t func_index,
                              uint32_t first_arg_reg);

#endif
