# Embed a `.jdll.abi` sidecar into a C translation unit for linking into a `.jdll`.
#
# Usage (inside add_custom_command):
#   cmake -DABI_FILE=/path/to/foo.jdll.abi -DOUT_C=/path/to/out.c -P EmbedJdllAbi.cmake

if(NOT ABI_FILE OR NOT OUT_C)
  message(FATAL_ERROR "EmbedJdllAbi.cmake requires ABI_FILE and OUT_C")
endif()

if(NOT EXISTS "${ABI_FILE}")
  message(FATAL_ERROR "ABI file not found: ${ABI_FILE}")
endif()

file(READ "${ABI_FILE}" _hex HEX)
string(LENGTH "${_hex}" _hex_len)
if(_hex_len EQUAL 0 OR _hex_len LESS 22)
  message(FATAL_ERROR "ABI file too small: ${ABI_FILE}")
endif()

math(EXPR _byte_count "${_hex_len} / 2")

set(_out "// Auto-generated by Jello build — do not edit.\n")
string(APPEND _out "#include <stdint.h>\n")
string(APPEND _out "#if defined(__APPLE__)\n")
string(APPEND _out "#define JDLL_ABI_SECTION __attribute__((section(\"__DATA,__jdll_abi\"), used, aligned(1)))\n")
string(APPEND _out "#elif defined(__linux__)\n")
string(APPEND _out "#define JDLL_ABI_SECTION __attribute__((section(\".jdll_abi\"), used, aligned(1)))\n")
string(APPEND _out "#else\n")
string(APPEND _out "#define JDLL_ABI_SECTION __attribute__((used, aligned(1)))\n")
string(APPEND _out "#endif\n\n")
string(APPEND _out "JDLL_ABI_SECTION\n")
string(APPEND _out "const uint8_t jello_jdll_abi_blob[] = {\n")

set(_line "  ")
foreach(_i RANGE 0 ${_byte_count})
  if(_i EQUAL _byte_count)
    break()
  endif()
  math(EXPR _pos "${_i} * 2")
  string(SUBSTRING "${_hex}" ${_pos} 2 _byte_hex)
  string(APPEND _line "0x${_byte_hex}, ")
  math(EXPR _mod "${_i} % 12")
  if(_mod EQUAL 11)
    string(APPEND _out "${_line}\n")
    set(_line "  ")
  endif()
endforeach()
if(NOT _line STREQUAL "  ")
  string(APPEND _out "${_line}\n")
endif()
string(APPEND _out "};\n")

file(WRITE "${OUT_C}" "${_out}")
